spring:
  data:
    cassandra:
      keyspace-name: main
      username: JzxkNFqiAXWeQNHfYaRhHIaE
      password: liFOAExJT4n43.t7Xvhplc2bEJHL9Ajt7BLTkarfqFXDkhjxIkN4eomGWeDs1cFdKxpAlsgOfbG0BlMYU-F2qgLTB,QG+B3mWZpmS,yAEhX370zteIYws2r,WqFva7S.
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: messaging-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.f5622341d8d71848
            client-secret: 8a586472d6df3ee69d51a22ad970d33e73735efa

datastax.astra:
  secure-connect-bundle: secure-connect-messaging-app.zip

astra:
  db:
    id: 60d30409-08ee-4bbf-a784-6e2b9631d63f-1
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:JzxkNFqiAXWeQNHfYaRhHIaE:926dbef0eca3eabd61185689260e0ed9dc8c1763ca1bc835bd3dd71d4a3f120f

